### ISSUE TITLE
When run typescript file I have - error TS2300

### ISSUE THREAD

**Issue by splincode** [google/zx#205]
## Expected Behavior

No error

## Actual Behavior

![image](https://user-images.githubusercontent.com/12021443/131028274-c9c38497-ac1f-45d4-8bc7-5bd4e4bd6050.png)

## Steps to Reproduce the Problem

```bash
$ yarn zx scripts/test.ts
```

```ts
#!/usr/bin/env zx
import { $, cd, nothrow } from 'zx';

void (async function (): Promise<void> {
    const { packages }: typeof import('../package.json') = require('../package.json');

    for (const packagePath of packages) {
        // eslint-disable-next-line no-console
        console.log(chalk.blue(`[TEST]: ${packagePath}`));
        cd(packagePath);
        await nothrow($`yarn pretest`);
        await nothrow($`yarn test`);
    }
})();

```

Examples:
https://github.com/Angular-RU/angular-ru-sdk/pull/852/checks?check_run_id=3436702574

**Comment by antonmedv** [comment]
Should be fixed in v4.

**Comment by splincode** [comment]
@antonmedv 
![image](https://user-images.githubusercontent.com/12021443/131308722-8045ad5d-f468-4215-a4dc-62e5a22d6eed.png)

after upgrade to v4 I have another problem with

`Consider using '--resolveJsonModule' to import module with '.json' extension`

and again I have - error TS2300

**Comment by antonmedv** [comment]
Seems working for me:
```ts
#!/usr/bin/env zx
import { $, cd, nothrow, chalk } from 'zx';

void (async function (): Promise<void> {
    const packages = require('./package.json');
    
    for (const packagePath of Object.keys(packages)) {
        // eslint-disable-next-line no-console
        console.log(chalk.blue(`[TEST]: ${packagePath}`));
        cd(packagePath);
        await nothrow($`yarn pretest`);
        await nothrow($`yarn test`);
    }
})();
```

Please, take closer look at your TS setup. Looks like something with it.

The zx only does this: 
https://github.com/google/zx/blob/f0b6c21a43d3ddeeb434763b6c1f3d487761e439/zx.mjs#L200

**Comment by splincode** [comment]
How cat I path custom tsconfig.json?)

**Comment by antonmedv** [comment]
You can use something like `ts-node` or your preferred was of converting ts->js. The zx has really limited ts support via running tsc. Also, from my understanding, tsc will use local tsconfig.json anyway.

**Comment by splincode** [comment]
`tsc will use local tsconfig.json anyway` but you can set `tsc --project tsconfig.tools.json`

**Comment by antonmedv** [comment]
Because ts used in so many different ways and setups, it difficult to support all of them. ¯\\\_(ツ)\_/¯

**Comment by antonmedv** [comment]
Most straightforward way is to use .mjs extension -> no compilation, esm modules, fastest start-up time. Good for scripting.
