### ISSUE TITLE
URL.parse, introduced in #1193, breaks compatibility with Node < v22.1.0

### ISSUE THREAD

**Issue by KieranHunt** [google/zx#1295]
Hey all!

As the title says, [fix\(jsr\): extract version from url by antongolub · Pull Request \#1193 · google\/zx](https://github.com/google/zx/pull/1193) (released in [Release 8.5.3 — Trap Master · google\/zx](https://github.com/google/zx/releases/tag/8.5.3)) seems to break compatibility with Node < v22.1.0.

[zx\/src\/index.ts at 4cd098058bb6a7f6afaf5950e8bca329de515244 · google\/zx](https://github.com/google/zx/blob/4cd098058bb6a7f6afaf5950e8bca329de515244/src/index.ts#L25) at line 25 uses `URL.parse`. But `URL.parse` was only added in Node v22.1.0 ([[URL | Node.js v24.4.1 Documentation](https://nodejs.org/api/url.html#urlparseinput-base)](https://nodejs.org/api/url.html#urlparseinput-base)). 

This broke for me in an environment running Node 18. With:

```
TypeError: URL.parse is not a function,
```

## To reproduce:

In `package.json`:

```json
{
  "name": "zx-node",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "zx": "^8.7.2"
  }
}
```

In `test.js`:

```js
import 'zx/globals'

$`echo "foo"`
```

Pull `zx` out of an environment where `../package.json` exists (see the line with the bug)

```bash
npx esbuild test.js --bundle --format=iife --platform=node > test-built.js
```

Switch to node 18:

```bash
nvm use v18.20.8
```

💥

```
node test-built.js                                                        
/Volumes/code/zx-node/test-built.js:22424
      })) == null ? void 0 : _a.version) || URL.parse(import_meta_url).pathname.split("/")[3];
                                                ^

TypeError: URL.parse is not a function
    at node_modules/zx/build/index.cjs (/Volumes/code/zx-node/test-built.js:22424:49)
    at __require2 (/Volumes/code/zx-node/test-built.js:15:52)
    at node_modules/zx/build/globals.cjs (/Volumes/code/zx-node/test-built.js:22442:24)
    at __require2 (/Volumes/code/zx-node/test-built.js:15:52)
    at /Volumes/code/zx-node/test-built.js:22466:28
    at Object.<anonymous> (/Volumes/code/zx-node/test-built.js:22471:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
```

Switch to a newer node:

```bash
nvm use v22.1.0    
Now using node v22.1.0 (npm v10.7.0)
```

💸

```
node test-built.js 
# No exception!
```

**Comment by antongolub** [comment]
Hey @KieranHunt,

I'm afraid, the bundler cannot guess that zx uses dynamic `package.json` load to obtain own version. Thats why `URL.parse` is triggered. I will replace this part with a static value.

**Comment by antongolub** [comment]
@KieranHunt, 

Check out [v8.8.0-dev.e18fe85](https://www.npmjs.com/package/zx/v/8.8.0-dev.e18fe85). It should work fine.

**Comment by KieranHunt** [comment]
Thanks @antongolub!

I updated and re-ran the build step. 
Node v18.20.8 now works! 

✨
